/**
 * Google Calendar
 * Version: 6.0 (Plugin Architecture — registers with SyncEngine)
 */

SyncEngine.registerTool('CALENDAR_SYNC', {
    REQUIRED_SERVICES: [ { name: 'Calendar API', test: function() { return typeof Calendar !== 'undefined'; } } ],
    SHEET_NAME: SHEET_NAMES.CALENDAR_SYNC,
    FROZEN_COLS: 2,
    TITLE: SHEET_NAMES.CALENDAR_SYNC,
    MENU_LABEL: SHEET_NAMES.CALENDAR_SYNC,
    MENU_ENTRYPOINT: 'CalendarSync_openSidebar',
    MENU_ORDER: 10,
    SIDEBAR_HTML: 'tools/CalendarSync/Sidebar',
    SIDEBAR_WIDTH: 400,
    FORMAT_CONFIG: {
        conditionalRules: [{ type: 'pending', actionCol: 'A', scope: 'actionOnly' }],
        COL_SCHEMA: [
            { header: 'Action', type: 'ACTION', options: ['CREATE', 'UPDATE', 'DELETE'] },
            { header: 'Status', type: 'STATUS' },
            { header: 'Calendar Name', type: 'DROPDOWN', options: function() { try { return CalendarApp.getAllCalendars().map(function(c){return c.getName()}); } catch(e) { return []; } } },
            { header: 'Event Title', type: 'TEXT' },
            { header: 'Start Time', type: 'TEXT' },
            { header: 'End Time', type: 'TEXT' },
            { header: 'Description', type: 'TEXT' },
            { header: 'Location', type: 'TEXT' },
            { header: 'Add Meet?', type: 'CHECKBOX' },
            { header: 'Guests', type: 'EMAIL_LIST' },
            { header: 'Color', type: 'DROPDOWN', options: function() { try { return ['Default'].concat(Object.keys(CalendarApp.EventColor)); } catch(e){ return ['Default']; } } },
            { header: 'Visibility', type: 'DROPDOWN', options: ['Default', 'Public', 'Private'] },
            { header: 'Event ID', type: 'ID' },
            { header: 'Calendar ID', type: 'ID' }
        ]
    },
    HELP_ITEMS: {
        gettingStarted: {
            title: "Getting Started",
            content: "<p><strong>Getting Started</strong></p><p>Follow these steps to sync events:</p><ol><li><strong>Define Actions:</strong> Set the Action column to <code>CREATE</code>, <code>UPDATE</code>, or <code>DELETE</code>.</li><li><strong>Specify Times:</strong> Ensure Start Time and End Time use standard date/time formats (e.g. <code>MM/dd/yyyy HH:mm:ss</code>).</li><li><strong>Push:</strong> Click <strong>Push Changes</strong> in the sidebar to synchronize with Google Calendar.</li></ol>"
        },
        items: [
            {
                icon: "help-circle",
                color: "var(--primary)",
                label: "Column Guide",
                shortDesc: "Understand event colors, guest emails, and Meet integration.",
                tooltipId: "help-columns-guide",
                tooltipContent: "<p><strong>Core Columns Guide</strong></p><ul><li><strong>Calendar Name:</strong> Must match one of your accessible calendars.</li><li><strong>Add Meet?:</strong> Tick to generate a Google Meet link for the event.</li><li><strong>Guests:</strong> Comma-separated list of guest email addresses.</li><li><strong>Event ID / Calendar ID:</strong> Read-only IDs generated by Google Calendar. Do not manually edit.</li></ul>"
            },
            {
                icon: "lightbulb",
                color: "var(--warning)",
                label: "Pro Tips",
                shortDesc: "Sync range limits, importing, and moving events.",
                tooltipId: "help-tips",
                tooltipContent: "<p><strong>Pro Tips</strong></p><ul><li><strong>Importing:</strong> Use <strong>Pull Events</strong> to import existing events from Google Calendar into the sheet.</li><li><strong>Moving Events:</strong> To move an event, change its <code>Calendar Name</code> and select <code>UPDATE</code> action.</li><li><strong>Time Formats:</strong> Supported formats include <code>YYYY-MM-DD HH:MM:SS</code> and standard regional formats.</li></ul>"
            }
        ]
    },
    ACTIONS: {
        getLoadData: function () {
            try {
                var allCalendars = _App_callWithBackoff(function () {
                    return CalendarApp.getAllCalendars();
                });
                var seen = {};
                var uniqueCals = [];

                (allCalendars || []).forEach(function (c) {
                    var calId = c && c.getId ? c.getId() : '';
                    if (!calId || seen[calId]) return;
                    seen[calId] = true;
                    uniqueCals.push({
                        id: calId,
                        name: c.getName(),
                        color: c.getColor()
                    });
                });

                var savedCalIds = _App_getProperty(APP_PROPS.CAL_SELECTED_IDS);
                if (!Array.isArray(savedCalIds)) savedCalIds = [];

                return _App_ok('Calendar load data ready.', {
                    calendars: uniqueCals,
                    savedCalIds: savedCalIds,
                    savedStartDate: _App_getProperty(APP_PROPS.CAL_START_DATE),
                    savedEndDate: _App_getProperty(APP_PROPS.CAL_END_DATE)
                });
            } catch (err) {
                throw new Error('Unable to load calendars. ' + err.message);
            }
        },
        savePreferences: function (calIds, startStr, endStr) {
            if (calIds) _App_setProperty(APP_PROPS.CAL_SELECTED_IDS, calIds);
            if (startStr !== undefined) _App_setProperty(APP_PROPS.CAL_START_DATE, startStr);
            if (endStr !== undefined) _App_setProperty(APP_PROPS.CAL_END_DATE, endStr);
            return _App_ok('Preferences saved.');
        },
        pull: function (request) {
            var TARGET_SHEET_NAME = SHEET_NAMES.CALENDAR_SYNC;
            var allCals = _App_callWithBackoff(function () { return CalendarApp.getAllCalendars(); });

            // Fetch Events
            var start = new Date(request.startDate);
            var end = new Date(request.endDate);
            var outputObjects = [];

            allCals.forEach(function (cal) {
                try {
                    var calName = cal.getName();
                    var calId = cal.getId();
                    var events = _App_callWithBackoff(function () { return cal.getEvents(start, end); });
                    events.forEach(function (e) {
                        outputObjects.push({
                            'Action': "",
                            'Calendar Name': calName,
                            'Event Title': e.getTitle(),
                            'Start Time': _App_formatDateTime(e.getStartTime()),
                            'End Time': _App_formatDateTime(e.getEndTime()),
                            'Description': e.getDescription(),
                            'Location': e.getLocation(),
                            'Add Meet?': false,
                            'Guests': e.getGuestList().map(function (g) { return g.getEmail(); }).join(","),
                            'Color': "Default",
                            'Visibility': "Default",
                            'Event ID': e.getId(),
                            'Calendar ID': calId
                        });
                    });
                } catch (err) {
                }
            });

            // Sort by Calendar Name
            outputObjects.sort(function (a, b) {
                var nameA = (a['Calendar Name'] || "").toLowerCase();
                var nameB = (b['Calendar Name'] || "").toLowerCase();
                if (nameA < nameB) return -1;
                if (nameA > nameB) return 1;
                return 0;
            });

            // Populate Sheet via DAO
            SheetManager.overwriteObjects('CALENDAR_SYNC', outputObjects);

            SyncEngine.getTool('CALENDAR_SYNC').ACTIONS.savePreferences(null, request.startDate, request.endDate);
            var summary = 'Successfully imported ' + outputObjects.length + " events into '" + TARGET_SHEET_NAME + "'.";
            return _App_ok(summary);
        },
        push: function () {
            var pendingItems = SheetManager.readPendingObjects('CALENDAR_SYNC');

            if (pendingItems.length === 0) return _App_ok("No pending actions found.");

            var allCals = CalendarApp.getAllCalendars();
            var calMap = new Map();
            var calObjMap = new Map();

            allCals.forEach(function (c) {
                calMap.set(c.getName(), c.getId());
                calObjMap.set(c.getId(), c);
            });

            var stats = _App_BatchProcessor('CALENDAR_SYNC', pendingItems, function (item) {
                var rowUpdates = {
                    action: item['Action'],
                    eventId: item['Event ID'] ? String(item['Event ID']) : null,
                    calId: item['Calendar ID'] ? String(item['Calendar ID']) : null,
                    status: "",
                    _rowNumber: item._rowNumber
                };

                var action = rowUpdates.action.toString().toUpperCase();
                var targetCalName = item['Calendar Name'];
                var targetCalId = calMap.get(targetCalName);

                var eventData = {
                    title: item['Event Title'],
                    start: item['Start Time'],
                    end: item['End Time'],
                    desc: item['Description'],
                    loc: item['Location'],
                    meet: item['Add Meet?'],
                    guests: item['Guests'],
                    color: item['Color'],
                    visibility: item['Visibility']
                };

                if (!(eventData.start instanceof Date)) eventData.start = new Date(eventData.start);
                if (!(eventData.end instanceof Date)) eventData.end = new Date(eventData.end);

                if (isNaN(eventData.start.getTime())) throw new Error("⚠️ Data Error: Invalid Start Time format");
                if (isNaN(eventData.end.getTime())) throw new Error("⚠️ Data Error: Invalid End Time format");
                if (eventData.end <= eventData.start) throw new Error("⚠️ Data Error: End Time cannot be before or equal to Start Time");
                if (!eventData.title) throw new Error("⚠️ Data Error: Missing Event Title");

                if (eventData.guests && !_App_validateEmailList(eventData.guests)) {
                    throw new Error("⚠️ Data Error: Invalid guest email address(es)");
                }

                switch (action) {
                    case "CREATE":
                        if (!targetCalName) throw new Error("⚠️ Data Error: Missing Calendar Name");
                        if (!targetCalId) throw new Error("⚠️ Data Error: Calendar '" + targetCalName + "' not found");

                        var createCal = calObjMap.get(targetCalId);
                        if (!createCal) throw new Error("❌ API Error: Target calendar object is null");

                        var newEvent = _App_callWithBackoff(function () {
                            return createCal.createEvent(eventData.title, eventData.start, eventData.end, {
                                description: eventData.desc,
                                location: eventData.loc,
                                guests: eventData.guests ? eventData.guests.split(',').map(function (g) { return g.trim(); }).join(',') : ""
                            });
                        });

                        var optionErr = _CalendarSync_applyEventOptions(newEvent, eventData);
                        if (eventData.meet === true || eventData.meet === 'TRUE') {
                            try { _CalendarSync_addMeetLinkToEvent(targetCalId, newEvent.getId()); }
                            catch (meetErr) { optionErr = optionErr ? optionErr + ", Meet: " + meetErr.message : "Meet: " + meetErr.message; }
                        }

                        rowUpdates.eventId = newEvent.getId();
                        rowUpdates.calId = targetCalId;
                        rowUpdates.status = _App_formatStatus('SUCCESS', "Created") + (optionErr ? " (" + _App_formatStatus('WARNING', optionErr) + ")" : "");
                        rowUpdates.action = "";
                        break;

                    case "UPDATE":
                        if (!rowUpdates.eventId) throw new Error("⚠️ Data Error: Missing Event ID");

                        // Identity Check: If target calendar name doesn't match Calendar ID, perform MOVE
                        if (targetCalId && rowUpdates.calId && targetCalId !== rowUpdates.calId) {
                            rowUpdates = _CalendarSync_processMove(rowUpdates, calObjMap, targetCalId, eventData);
                            break;
                        }

                        var updateCal = calObjMap.get(rowUpdates.calId);
                        if (!updateCal) throw new Error("⚠️ Data Error: Calendar ID not found on your account");

                        var eventToUpdate = null;
                        try { eventToUpdate = _App_callWithBackoff(function() { return updateCal.getEventById(rowUpdates.eventId); }); } catch(e) {}

                        if (!eventToUpdate) throw new Error("⚠️ Data Error: Event ID not found on calendar");

                        _App_callWithBackoff(function () {
                            if (eventToUpdate.getTitle() !== eventData.title) {
                                eventToUpdate.setTitle(eventData.title);
                            }
                            var currentStart = eventToUpdate.getStartTime();
                            var currentEnd = eventToUpdate.getEndTime();
                            if (currentStart.getTime() !== eventData.start.getTime() || currentEnd.getTime() !== eventData.end.getTime()) {
                                eventToUpdate.setTime(eventData.start, eventData.end);
                            }
                            if (eventToUpdate.getDescription() !== eventData.desc) {
                                eventToUpdate.setDescription(eventData.desc);
                            }
                            if (eventToUpdate.getLocation() !== eventData.loc) {
                                eventToUpdate.setLocation(eventData.loc);
                            }
                        });

                        var updateOptionErr = _CalendarSync_applyEventOptions(eventToUpdate, eventData);
                        if (eventData.meet === true || eventData.meet === 'TRUE') {
                            try { _CalendarSync_addMeetLinkToEvent(rowUpdates.calId || eventToUpdate.getOriginalCalendarId(), rowUpdates.eventId); }
                            catch (meetErr) { updateOptionErr = updateOptionErr ? updateOptionErr + ", Meet: " + meetErr.message : "Meet: " + meetErr.message; }
                        }

                        var currentGuests = eventToUpdate.getGuestList();
                        var targetGuests = eventData.guests ? eventData.guests.split(',').map(function (g) { return g.trim(); }).filter(function (g) { return g !== ""; }) : [];
                        var currentEmails = currentGuests.map(function(g) { return g.getEmail().toLowerCase(); });

                        currentGuests.forEach(function (guestObj) {
                            var email = guestObj.getEmail();
                            if (targetGuests.map(function(t) { return t.toLowerCase(); }).indexOf(email.toLowerCase()) === -1) {
                                eventToUpdate.removeGuest(email);
                            }
                        });
                        targetGuests.forEach(function (email) {
                            if (currentEmails.indexOf(email.toLowerCase()) === -1) {
                                eventToUpdate.addGuest(email);
                            }
                        });

                        rowUpdates.status = _App_formatStatus('SUCCESS', "Updated") + (updateOptionErr ? " (" + _App_formatStatus('WARNING', updateOptionErr) + ")" : "");
                        rowUpdates.action = "";
                        break;

                    case "DELETE":
                        if (!rowUpdates.eventId) throw new Error("⚠️ Data Error: Missing Event ID");
                        var delCal = calObjMap.get(rowUpdates.calId);
                        if (!delCal) throw new Error("⚠️ Data Error: Original Calendar inaccessible");

                        var eventToDel = null;
                        try { eventToDel = _App_callWithBackoff(function() { return delCal.getEventById(rowUpdates.eventId); }); } catch(e) {}

                        if (eventToDel) {
                            _App_callWithBackoff(function () { eventToDel.deleteEvent(); });
                            rowUpdates.status = _App_formatStatus('SUCCESS', "Deleted");
                            rowUpdates.action = "";
                        } else {
                            rowUpdates.status = _App_formatStatus('WARNING', "Already Deleted (Event not found)");
                            rowUpdates.action = "";
                        }
                        break;

                    default:
                        rowUpdates.status = _App_formatStatus('WARNING', "Unknown Action '" + action + "'");
                }

                return rowUpdates;

            }, {
                onBatchComplete: function (batchResults) {
                    _App_batchPatchResults('CALENDAR_SYNC', batchResults, function (res) {
                        return {
                            'Event ID': res.eventId,
                            'Calendar ID': res.calId
                        };
                    });
                }
            });

            return _App_ok("Sync Complete. Processed: " + stats.processedCount);
        }
    }
});

// --- MENU & UI HANDLERS ---

/** Opens the Calendar sidebar and ensures the sheet exists. */
function CalendarSync_openSidebar() {
  return Logger.run('CALENDAR_SYNC', 'Open Sidebar', function () {
    _App_launchTool('CALENDAR_SYNC');
  });
}

// --- HELPER VALIDATORS ---

function _CalendarSync_processMove(rowUpdates, calObjMap, targetCalId, eventData) {
  var oldCal = calObjMap.get(rowUpdates.calId);
  var newCal = calObjMap.get(targetCalId);

  if (!newCal) throw new Error("⚠️ Data Error: Target calendar not accessible");

  var newEvent = newCal.createEvent(eventData.title, eventData.start, eventData.end, {
    description: eventData.desc,
    location: eventData.loc,
    guests: eventData.guests ? eventData.guests.split(',').map(function (g) { return g.trim(); }).join(',') : ""
  });
  _CalendarSync_applyEventOptions(newEvent, eventData);

  var meetWarning = "";
  if (eventData.meet === true || eventData.meet === 'TRUE') {
    try { _CalendarSync_addMeetLinkToEvent(targetCalId, newEvent.getId()); }
    catch (meetErr) { meetWarning = " (⚠️ Meet: " + meetErr.message + ")"; }
  }

  var deleteWarning = "";
  if (oldCal && rowUpdates.eventId) {
    try {
      var oldEvent = null;
      try { oldEvent = _App_callWithBackoff(function() { return oldCal.getEventById(rowUpdates.eventId); }); } catch(e) {}
      if (oldEvent) oldEvent.deleteEvent();
      else deleteWarning = " (⚠️ Old event not found)";
    } catch (delErr) {
      deleteWarning = " (⚠️ Could not delete old event: " + delErr.message + ")";
    }
  } else {
    deleteWarning = " (⚠️ Old calendar inaccessible)";
  }

  rowUpdates.eventId = newEvent.getId();
  rowUpdates.calId = targetCalId;
  rowUpdates.status = _App_formatStatus('SUCCESS', "Moved") + deleteWarning + meetWarning;
  rowUpdates.action = "";
  return rowUpdates;
}

function _CalendarSync_applyEventOptions(event, data) {
  var warning = null;
  if (data.color && data.color !== 'Default') {
    if (CalendarApp.EventColor[data.color]) {
      try {
        var targetColor = CalendarApp.EventColor[data.color];
        if (event.getColor() !== targetColor) {
          event.setColor(targetColor);
        }
      } catch (e) { warning = "Color set failed"; }
    } else {
      warning = "Invalid Color";
    }
  }
  if (data.visibility) {
    try {
      var targetVisibility = null;
      if (data.visibility === 'Public') targetVisibility = CalendarApp.Visibility.PUBLIC;
      else if (data.visibility === 'Private') targetVisibility = CalendarApp.Visibility.PRIVATE;
      
      if (targetVisibility !== null && event.getVisibility() !== targetVisibility) {
        event.setVisibility(targetVisibility);
      }
    } catch (e) {
      warning = warning ? warning + ", Visibility set failed" : "Visibility set failed";
    }
  }
  return warning;
}

// --- UTILITIES ---

function _CalendarSync_addMeetLinkToEvent(calendarId, eventId) {
  if (typeof Calendar === 'undefined') {
    throw new Error("Enable 'Google Calendar API' in Services");
  }
  Calendar.Events.patch({
    conferenceData: {
      createRequest: {
        requestId: Utilities.getUuid(),
        conferenceSolutionKey: { type: "hangoutsMeet" }
      }
    }
  }, calendarId, eventId, { conferenceDataVersion: 1 });
}
